### ISSUE TITLE
Quesition on self.sess and self.tf_sess

### ISSUE THREAD

**Issue by dragen1860** [brain-research/acai#4]
Hi, dear author:
I wonder what's difference between `self.sess` and `self.tf_sess`?
I DNT understand why you use `x = self.tf_sess.run(data)` to run `data` op while using  `self.sess.run(ops.train_op, feed_dict={ops.x: x, ops.label: label})` to run `ops.train_op`?
Could you give me some illustrations?

In file lib/train.py:
```
    @property
    def tf_sess(self):
        return self.sess._tf_sess()

    def train_step(self, data, ops):
        x = self.tf_sess.run(data)
        x, label = x['x'], x['label']
        self.sess.run(ops.train_op, feed_dict={ops.x: x, ops.label: label})
```

**Comment by david-berthelot** [comment]
`sess` is monitored while `tf_sess` is not.
In practice, it means that `sess.run` calls the session hooks (for summaries in particular) while `ts_sess.run` does not.

**Comment by dragen1860** [comment]
Thanks. @david-berthelot 
Im not an expert in tensorflow. Hence I wonder can I use `self.sess` instead of `self.sess._tf_sess()` for all codes.
What's the consequence if that.

**Comment by david-berthelot** [comment]
I was getting an error from Tensorflow when using self.sess for the data reading, that's why I had to use tf.sess._tf_sess() to work around it. I forgot the exact details of what the error message was.

But feel free to reimplement stuff your own way, the most important part is the code in acai.py (and the other models if you're interested in them as well).
